W4D4/config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]

  root to: redirect("/cats")
end

W4D4/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Amatic+SC:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<nav class="main-nav">
<h1><%= link_to "99 Cats", cats_url %></h1>
<div>
<% if current_user.nil? %>
  <%= link_to "Sign in", new_session_url %>
  <%= link_to "Sign up", new_user_url %>
<% else %>
  <%= current_user.username %>
  <%= button_to "Logout", session_url, method: :delete %>
<% end %>
</div>
</nav>

<main>
  <%= yield %>
</main>

<footer>
  This is our 99 cats site. Feel free to look around.

  <%= yield :footer %>
</footer>
</body>
</html>

W4D4/app/views/layouts/welcome_email.text.erb
  Hey <%= @user.username %>
===============================================

  You did a lot today.  We made auth from scratch,
  sat in a hot lecture room, and managed to still
  have a ton of homework left.

  Congratulations


  Check out this link on bootcamps: <%= @url %>

  See you bright and early...
===============================================