W4D2/ninetyninecats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests do
    member do
      get 'approve'
      get 'deny'
    end
  end
end

W4D2/ninetyninecats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime
#  updated_at  :datetime
#

class Cat < ActiveRecord::Base
  COLORS = %w[black white orange grey brown]
  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS,
              message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w(M F), message: "%{value} is not a valid sex" }

  has_many :cat_rental_requests,
      class_name: :CatRentalRequest,
      primary_key: :id,
      foreign_key: :cat_id,
      dependent: :destroy

  def age
    Date.today.year - birth_date.year
  end




end

W4D2/ninetyninecats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: %w(PENDING APPROVED DENIED),
            message: "%{value} is not a valid status" }
  validate :does_not_overlap_approved_request
  validate :start_date_earlier_than_end_date

  belongs_to :cat,
    class_name: :Cat,
    primary_key: :id,
    foreign_key: :cat_id

  def approve!
    transaction do
      unless overlapping_approved_requests.exists?
        self.status = "APPROVED"
        overlapping_pending_requests.each do |request|
          request.deny!
        end
      else
        self.status = "DENIED"
      end

      save
    end
  end

  def deny!
    self.status = "DENIED"
    save
  end

  def pending?
    self.status == "PENDING"
  end

  private

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_requests
      CatRentalRequest
        .where.not(id: self.id)
        .where("cat_id = ?", cat_id)
        .where.not("end_date < ? OR start_date > ?", start_date, end_date)
  end

  def does_not_overlap_approved_request
    if overlapping_approved_requests.exists?
      errors[:base] << "Overlaps with approved requests"
    end
  end

  def start_date_earlier_than_end_date
    unless start_date < end_date
      errors[:base] << "Start date must be before end date!"
    end
  end
end

W4D2/ninetyninecats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

W4D2/ninetyninecats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    @cat_request = CatRentalRequest.new
    render :new
  end

  def create
    request = CatRentalRequest.new(cat_request_params)

    if request.save
      redirect_to cat_url(request.cat)
    else
      render json: request.errors.full_messages, status: 422
    end
  end

  def approve
    request = CatRentalRequest.find(params[:id])
    request.approve!
    redirect_to cat_url(request.cat)
  end

  def deny
    request = CatRentalRequest.find(params[:id])
    request.deny!
    redirect_to cat_url(request.cat)
  end

  private

  def cat_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
  end
end

W4D2/ninetyninecats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    @cat_requests = @cat.cat_rental_requests.order(:start_date)
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    cat = Cat.new(cat_params)

    if cat.save
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    cat = Cat.find(params[:id])
    if cat.update(cat_params)
      redirect_to cat_url(cat)
    else
      render json: cat.errors.full_messages, status: :unprocessable_entity
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

W4D2/ninetyninecats/app/helpers/cats_helper.rb
module CatsHelper
end

W4D2/ninetyninecats/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">

  <label for="cat">Cat</label>
  <select id="cat" name="cat_rental_request[cat_id]">
    <option value="blank" selected disabled>-- Please select a cat --</option>
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label for="start_date">start date</label>
  <input id="start_date" type="date" name="cat_rental_request[start_date]" value="<%= Date.today %>">
  <br>

  <label for="end_date">end date</label>
  <input id="end_date" type="date" name="cat_rental_request[end_date]" value="<%= Date.today %>">
  <br>

  <input type="submit" value="Rent Cat!">

</form>

W4D2/ninetyninecats/app/views/cats/_form.html.erb
<% persisted = cat.persisted? %>
<% action_url = persisted ? cat_url(cat) : cats_url %>
<% button_text = persisted ? "Update Cat" : "Create Cat" %>

<form action="<%= action_url %>" method="post">
  <% if persisted %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  <br>

  <label for="sex">Sex</label>
  M<input id="sex" type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %>>
  F<input id="sex" type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>>
  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option value="blank" <%= persisted ? "" : "selected" %> disabled>-- Please select a color --</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%= color %>" <%= color == cat.color ? "selected" : "" %>><%= color %></option>
    <% end %>
  </select>
  <br>

  <label for="date">Birth date</label>
  <input id="date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  <br>

  <label for="description">Description</label>
  <br>

  <textarea id="description" name="cat[description]" rows="10" cols="30">
    <%= cat.description %>
  </textarea>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>

W4D2/ninetyninecats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat %>

W4D2/ninetyninecats/app/views/cats/index.html.erb
<% @cats.each do |cat| %>
  <ul>
    <li>
      <a href="<%= cat_url(cat) %>"><%= cat.name %></a>
    </li>
  </ul>
<% end %>

W4D2/ninetyninecats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat %>

W4D2/ninetyninecats/app/views/cats/show.html.erb
<table>
  <tr>
    <th>Name</th>
    <td><%= @cat.name %></td>
  </tr>

  <tr>
    <th>Color</th>
    <td><%= @cat.color %></td>
  </tr>

  <tr>
    <th>Sex</th>
    <td><%= @cat.sex %></td>

  </tr>

  <tr>
    <th>Age</th>
    <td><%= @cat.age %></td>
  </tr>

  <tr>
    <th>Description</th>
    <td><%= @cat.description %></td>
  </tr>

  <tr>
    <th>Rentals</th>
  </tr>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
  </tr>

  <% @cat_requests.each do |request| %>
  <tr>
  <td><%= request.start_date %></td>
  <td><%= request.end_date %></td>

  <% if request.pending? %>
  <td>
    <form action="<%= approve_cat_rental_request_url(request) %>">
      <input type="submit" value="Approve">
    </form>
    </td>
    <td>
    <form action="<%= deny_cat_rental_request_url(request) %>">
      <input type="submit" value="Deny">
    </form>
  <% end %>
  </td>
  </tr>
  <% end %>
</tr>

</table>